Set None as default for Optional fields
Optional and Required have different semantics, and the [Pydantic v2 cleanup](https://docs.pydantic.dev/latest/blog/pydantic-v2/#required-vs-nullable-cleanup) makes the fields required unless None is set as default value.

Without adding `= None` in those optional fields, the library fails, e.g.:

```
pydantic_core._pydantic_core.ValidationError: 2 validation errors for KeycloakUser
realmRoles
  Field required [type=missing, input_value={'id': '898e45fa-d868-4b3...: True, 'manage': True}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
attributes
  Field required [type=missing, input_value={'id': '898e45fa-d868-4b3...: True, 'manage': True}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
```